// Mocks generated by Mockito 5.0.16 from annotations
// in todos/test/features/todo_list/data/datasources/remote/todo_remote_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todos/src/core/network/dio_client.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [DioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioClient extends _i1.Mock implements _i2.DioClient {
  MockDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Response<T>?> get<T>(String? uri,
          {bool? authorized = true,
          String? authorizationToken,
          Map<String, dynamic>? queryParameters,
          _i4.Options? options,
          _i4.CancelToken? cancelToken,
          _i4.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#get, [
                uri
              ], {
                #authorized: authorized,
                #authorizationToken: authorizationToken,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i4.Response<T>?>.value())
          as _i3.Future<_i4.Response<T>?>);
  @override
  _i3.Future<_i4.Response<T>?> post<T>(String? uri,
          {bool? authorized = true,
          dynamic data,
          String? authorizationToken,
          Map<String, dynamic>? queryParameters,
          _i4.Options? options,
          _i4.CancelToken? cancelToken,
          _i4.ProgressCallback? onSendProgress,
          _i4.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [
                uri
              ], {
                #authorized: authorized,
                #data: data,
                #authorizationToken: authorizationToken,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i4.Response<T>?>.value())
          as _i3.Future<_i4.Response<T>?>);
  @override
  _i3.Future<_i4.Response<T>?> put<T>(String? uri,
          {bool? authorized = true,
          dynamic data,
          String? authorizationToken,
          Map<String, dynamic>? queryParameters,
          _i4.Options? options,
          _i4.CancelToken? cancelToken,
          _i4.ProgressCallback? onSendProgress,
          _i4.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [
                uri
              ], {
                #authorized: authorized,
                #data: data,
                #authorizationToken: authorizationToken,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i4.Response<T>?>.value())
          as _i3.Future<_i4.Response<T>?>);
  @override
  _i3.Future<_i4.Response<T>?> patch<T>(String? uri,
          {bool? authorized = true,
          dynamic data,
          String? authorizationToken,
          Map<String, dynamic>? queryParameters,
          _i4.Options? options,
          _i4.CancelToken? cancelToken,
          _i4.ProgressCallback? onSendProgress,
          _i4.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [
                uri
              ], {
                #authorized: authorized,
                #data: data,
                #authorizationToken: authorizationToken,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i4.Response<T>?>.value())
          as _i3.Future<_i4.Response<T>?>);
  @override
  _i3.Future<_i4.Response<T>?> delete<T>(String? uri,
          {bool? authorized = true,
          dynamic data,
          String? authorizationToken,
          Map<String, dynamic>? queryParameters,
          _i4.Options? options,
          _i4.CancelToken? cancelToken}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [
                uri
              ], {
                #authorized: authorized,
                #data: data,
                #authorizationToken: authorizationToken,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken
              }),
              returnValue: Future<_i4.Response<T>?>.value())
          as _i3.Future<_i4.Response<T>?>);
  @override
  String toString() => super.toString();
}
